# Generated by Django 6.1.1 on 2026-09-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model', models.CharField(max_length=50, verbose_name='الموديل')),
                ('year', models.IntegerField(verbose_name='سنة الصنع')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المشكلة/الخدمة')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='التكلفة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري الصيانة'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='تاريخ ووقت الموعد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مؤكد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
