# Generated by Django 6.1.1 on 2026-09-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار 🟡'), ('completed', 'مكتمل 🟢'), ('canceled', 'ملغى 🔴')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vehicles.vehicle', verbose_name='السيارة'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(verbose_name='سنة الصنع'),
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
    ]
