# Generated by Django 6.1.1 on 2026-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
