# Generated by Django 6.1.1 on 2026-09-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_appointment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='سنة الصنع'),
        ),
    ]
